# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'GroceryStoreFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroceryStoreFirebase

  pod 'Firebase/Analytics'

  pod 'Firebase/Firestore'

  pod 'FirebaseFirestoreSwift'

end
